apiVersion: v1
kind: ReplicationController
metadata:
  name: mosquitto
spec:
  replicas: 2
  selector:
    app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: kairen/mosquitto-pod-bridge:0.1.0
        env:
          - name: K8S_API_SERVER_IP
              value: localhost
          - name: K8S_API_SERVER_PORT
              value: localhost
          - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          - name: POD_METADATA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        ports:
        - containerPort: 1883
