apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: mosquitto
  name: mosquitto
spec:
  replicas: 1
  selector:
      run: mosquitto
  template:
    metadata:
      labels:
        run: mosquitto
    spec:
      containers:
        - name: mosquitto
          env:
            - name: K8S_API_SERVER_IP
              value: "localhost"
            - name: K8S_API_SERVER_PORT
              value: "8080"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_METADATA_NAME
              value: "mosquitto"
          image: kairen/mosquitto-pod-bridge:0.1.0
          ports:
            - containerPort: 1883
