apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  replicas: 2
  selector:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
          env:
            - name: K8S_API_SERVER_IP
              value: localhost
            - name: K8S_API_SERVER_PORT
              value: localhost
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: kairen/mosquitto-pod-bridge:0.1.0
          name: mosquitto
          ports:
            - containerPort: 1883
